import { RootDashboardContextProvider } from "@/components/context/root-dashboard-context";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootDashboardContextProvider>{children}</RootDashboardContextProvider>
    // <div>{children}</div>
  );
}
